// Mock data for the Rasul admin appointment screen

const APPOINTMENTS = [
  {
    id: 'a01',
    time: '08:30',
    end: '09:00',
    patient: 'Amara Okeke',
    age: 34, sex: 'F',
    reason: 'Follow-up · Hypertension',
    doctor: 'Dr. Ibrahim Musa',
    specialty: 'Cardiology',
    room: 'Room 204',
    status: 'checked-in',
    avatar: 'AO',
    tone: 'peach',
    note: 'Routine BP review. Bring prior ECG.',
    amount: '₦ 18,000',
  },
  {
    id: 'a02',
    time: '09:00',
    end: '09:30',
    patient: 'Samuel Adeyemi',
    age: 41, sex: 'M',
    reason: 'New consult · Chest pain',
    doctor: 'Dr. Ibrahim Musa',
    specialty: 'Cardiology',
    room: 'Room 204',
    status: 'confirmed',
    avatar: 'SA',
    tone: 'mint',
    note: 'First visit. Referred by GP.',
    amount: '₦ 24,000',
  },
  {
    id: 'a03',
    time: '09:45',
    end: '10:15',
    patient: 'Ngozi Eze',
    age: 28, sex: 'F',
    reason: 'Prenatal check · 24 wk',
    doctor: 'Dr. Funke Adebayo',
    specialty: 'Obstetrics',
    room: 'Room 112',
    status: 'confirmed',
    avatar: 'NE',
    tone: 'lilac',
    note: 'Glucose screening scheduled.',
    amount: '₦ 22,000',
  },
  {
    id: 'a04',
    time: '10:30',
    end: '11:00',
    patient: 'Kelechi Obi',
    age: 52, sex: 'M',
    reason: 'MRI review',
    doctor: 'Dr. Tunde Balogun',
    specialty: 'Neurology',
    room: 'Room 308',
    status: 'pending',
    avatar: 'KO',
    tone: 'heart',
    note: 'Awaiting patient confirmation.',
    amount: '₦ 32,000',
  },
  {
    id: 'a05',
    time: '11:15',
    end: '11:45',
    patient: 'Halima Bello',
    age: 7, sex: 'F',
    reason: 'Vaccination · MMR',
    doctor: 'Dr. Chioma Nwosu',
    specialty: 'Pediatrics',
    room: 'Room 101',
    status: 'confirmed',
    avatar: 'HB',
    tone: 'mint',
    note: 'Guardian will accompany.',
    amount: '₦ 9,500',
  },
  {
    id: 'a06',
    time: '12:00',
    end: '12:30',
    patient: 'David Umeh',
    age: 63, sex: 'M',
    reason: 'Post-op check · Knee',
    doctor: 'Dr. Ibrahim Musa',
    specialty: 'Orthopedics',
    room: 'Room 210',
    status: 'no-show',
    avatar: 'DU',
    tone: 'peach',
    note: 'Missed 2 prior calls.',
    amount: '₦ 16,000',
  },
  {
    id: 'a07',
    time: '13:30',
    end: '14:00',
    patient: 'Fatima Sani',
    age: 19, sex: 'F',
    reason: 'Skin consult',
    doctor: 'Dr. Ade Cole',
    specialty: 'Dermatology',
    room: 'Room 117',
    status: 'confirmed',
    avatar: 'FS',
    tone: 'lilac',
    note: '',
    amount: '₦ 14,000',
  },
];

const DOCTORS = [
  { id: 'd1', name: 'Dr. Ibrahim Musa', specialty: 'Cardiology', count: 6 },
  { id: 'd2', name: 'Dr. Funke Adebayo', specialty: 'Obstetrics', count: 4 },
  { id: 'd3', name: 'Dr. Tunde Balogun', specialty: 'Neurology', count: 3 },
  { id: 'd4', name: 'Dr. Chioma Nwosu', specialty: 'Pediatrics', count: 5 },
  { id: 'd5', name: 'Dr. Ade Cole',     specialty: 'Dermatology', count: 4 },
];

const STATS = {
  total: 24,
  checkedIn: 7,
  pending: 3,
  noShow: 1,
  revenue: '₦ 318k',
};

const STATUS_META = {
  'confirmed':   { label: 'Confirmed',  fg: 'var(--accent-ink)', bg: 'var(--accent-soft)', dot: 'var(--accent)' },
  'checked-in':  { label: 'Checked-in', fg: '#0A6B55',           bg: 'var(--success-soft)', dot: 'var(--success)' },
  'pending':     { label: 'Pending',    fg: '#8A6318',           bg: 'var(--warn-soft)',    dot: 'var(--warn)' },
  'no-show':     { label: 'No-show',    fg: '#9B2B2B',           bg: 'var(--danger-soft)',  dot: 'var(--danger)' },
  'cancelled':   { label: 'Cancelled',  fg: '#4B5262',           bg: '#ECEEF2',             dot: '#8A93A6' },
};

const TONES = {
  heart: 'var(--pastel-heart)',
  peach: 'var(--pastel-peach)',
  lilac: 'var(--pastel-lilac)',
  mint:  'var(--pastel-mint)',
};

Object.assign(window, { APPOINTMENTS, DOCTORS, STATS, STATUS_META, TONES });
